INSERT INTO USERS (ID,USER_NAME,PASSWORD,EMAIL) VALUES (1,'Marcel','Marcel','marcel.dragon@o2.pl');
INSERT INTO USERS (ID,USER_NAME,PASSWORD,EMAIL) VALUES (2,'Adam','Adam','adam.dragon@o2.pl');

INSERT INTO ROLES (ID,NAME) VALUES (1,'admin');
INSERT INTO ROLES (ID,NAME) VALUES (2,'user');

INSERT INTO USER_ROLE (USER_ID,ROLE_ID) VALUES (1,1);
INSERT INTO USER_ROLE (USER_ID,ROLE_ID) VALUES (2,2);